cache:
- C:\msys64\mkl-dnn-86b7129

platform:
- x64

install:
- git submodule update --init
- set PATH=C:\msys64\mingw64\bin;C:\msys64\usr\bin;%PATH%
#- pacman -Syu --noconfirm
- pacman -S --needed --noconfirm mingw-w64-x86_64-toolchain mingw-w64-x86_64-cmake mingw-w64-x86_64-opencv mingw-w64-x86_64-protobuf mingw-w64-x86_64-python3 mingw-w64-x86_64-python3-pip mingw-w64-x86_64-python3-numpy mingw-w64-x86_64-hdf5 mingw-w64-x86_64-ca-certificates
- set SSL_CERT_FILE=C:\msys64\mingw64\ssl\cert.pem
- set SSL_CERT_DIR=C:\msys64\mingw64\ssl\certs

- curl -omingw-w64-x86_64-mkl-dnn-0.14-3-x86_64.pkg.tar.xz -L https://www.dropbox.com/s/tpbwjcc0hz1uo7p/mingw-w64-x86_64-mkl-dnn-0.14-3-x86_64.pkg.tar.xz?dl=1
- pacman -U --noconfirm mingw-w64-x86_64-mkl-dnn-0.14-3-x86_64.pkg.tar.xz

- pip3 install --user chainer
- mkdir -p data
- python3 retrieve_data.py
- python3 gen_test_data.py

build_script:
- mkdir build
- cd build
- cmake -G "MSYS Makefiles" -DENABLE_TEST=ON -DCMAKE_INSTALL_PREFIX=/mingw64 ..
- make
# to find libmenoh.dll, libgtest.dll and libgtest_main.dll
- set PATH=C:\projects\menoh\build\menoh;C:\projects\menoh\build\test\lib\googletest\googlemock\gtest;%PATH%
- ldd test/menoh_test.exe
- ldd /c/projects/menoh/build/menoh/libmenoh.dll
- ldd /mingw64/bin/libmkldnn.dll
- test\menoh_test
